/**
 * Import a bible directory (bible-info.json, bible-books.json,
 * bible-chapters.json, bible-verses.json — the same shape as minimal.zip)
 * into a running BibleLib API.
 *
 * Usage:
 *   node scripts/import-bible.js <path-to-bible-dir> [baseUrl] [apiKey]
 *
 * Example:
 *   node scripts/import-bible.js ./minimal http://localhost:4000/api/v1 my-secret-key
 */

const fs = require('fs');
const path = require('path');

const dir = process.argv[2];
const baseUrl = process.argv[3] || 'http://localhost:4000/api/v1';
const apiKey = process.argv[4] || process.env.API_KEY || '';

if (!dir) {
  console.error('Usage: node scripts/import-bible.js <path-to-bible-dir> [baseUrl] [apiKey]');
  process.exit(1);
}

const readJson = (file) => JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8'));

const headers = {
  'Content-Type': 'application/json',
  ...(apiKey && { 'x-api-key': apiKey }),
};

async function request(method, url, body) {
  const res = await fetch(url, {
    method,
    headers,
    ...(body !== undefined && { body: JSON.stringify(body) }),
  });
  const data = await res.json();
  if (!res.ok) {
    throw new Error(`${method} ${url} -> ${res.status}: ${JSON.stringify(data)}`);
  }
  return data;
}

async function main() {
  // 1. Create the bible — bibleId is generated by the API.
  const info = readJson('bible-info.json').data;
  // Strip the source `id`/`dblId`/`updatedAt` — BibleLib generates its own id.
  const { id: _ignoreId, ...bibleInfo } = info;

  const createRes = await request('POST', `${baseUrl}/bibles`, bibleInfo);
  const bibleId = createRes.data.id;
  console.log(`Created bible: ${bibleId} (${createRes.data.name})`);

  // 2. Bulk-create books.
  const books = readJson('bible-books.json').data.map(({ bibleId: _b, ...book }) => book);
  const booksRes = await request('POST', `${baseUrl}/books/${bibleId}`, books);
  console.log(`Books: ${booksRes.message}`);

  // 3. Bulk-create chapters (flatten the per-book arrays into one list).
  const chaptersByBook = readJson('bible-chapters.json');
  const chapters = Object.values(chaptersByBook)
    .flat()
    .map(({ bibleId: _b, ...chapter }) => chapter);
  const chaptersRes = await request('POST', `${baseUrl}/chapters/${bibleId}`, chapters);
  console.log(`Chapters: ${chaptersRes.message}`);

  // 4. Bulk-create verse content (flatten the per-book, per-chapter objects).
  const versesByBook = readJson('bible-verses.json');
  const verses = Object.values(versesByBook)
    .flatMap((chaptersObj) => Object.values(chaptersObj))
    .map(({ bibleId: _b, ...verse }) => verse);

  // Verse content can be large — send it in batches.
  // NOTE: the bulk endpoints are rate-limited to 10 requests / 15 min per IP
  // by default. For a full 66-book bible (~1,200 chapters) you'll likely
  // want to raise BATCH_SIZE and/or temporarily increase `bulkLimiter`'s
  // `max` in src/middleware/rateLimit.ts.
  const BATCH_SIZE = 100;
  for (let i = 0; i < verses.length; i += BATCH_SIZE) {
    const batch = verses.slice(i, i + BATCH_SIZE);
    const versesRes = await request('POST', `${baseUrl}/verses/${bibleId}`, batch);
    console.log(`Verses batch ${i / BATCH_SIZE + 1}: ${versesRes.message}`);
  }

  console.log('\nDone! Your new bibleId is:', bibleId);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
