import mongoose, { Schema, Document } from 'mongoose';

export interface ILanguage {
  id: string;
  name: string;
  nameLocal?: string;
  script?: string;
  scriptDirection?: string;
}

export interface ICountry {
  id: string;
  name: string;
  nameLocal?: string;
}

export interface IBible extends Document {
  _id: string;          // bibleId — generated by BibleLib, e.g. "78a9f6124f344018-01"
  dblId?: string;
  relatedDbl?: string | null;
  name: string;
  nameLocal?: string;
  abbreviation: string;
  abbreviationLocal?: string;
  description?: string;
  descriptionLocal?: string;
  language: ILanguage;
  countries?: ICountry[];
  type?: string;
  copyright?: string;
  info?: string;
  audioBibles?: any[];
  created: Date;
  updated?: Date;
  updatedAt?: Date; // mirrors the source `updatedAt` field used by the upstream format
}

const languageSchema = new Schema<ILanguage>(
  {
    id: { type: String, required: true, trim: true },
    name: { type: String, required: true, trim: true },
    nameLocal: { type: String, trim: true },
    script: { type: String, trim: true },
    scriptDirection: { type: String, trim: true, default: 'LTR' },
  },
  { _id: false }
);

const countrySchema = new Schema<ICountry>(
  {
    id: { type: String, required: true, trim: true },
    name: { type: String, required: true, trim: true },
    nameLocal: { type: String, trim: true },
  },
  { _id: false }
);

const bibleSchema = new Schema<IBible>({
  _id: {
    type: String,
    trim: true,
  },
  dblId: {
    type: String,
    trim: true,
  },
  relatedDbl: {
    type: String,
    default: null,
  },
  name: {
    type: String,
    required: [true, 'name is required'],
    trim: true,
    maxlength: [200, 'name cannot exceed 200 characters'],
  },
  nameLocal: {
    type: String,
    trim: true,
  },
  abbreviation: {
    type: String,
    required: [true, 'abbreviation is required'],
    trim: true,
    maxlength: [20, 'abbreviation cannot exceed 20 characters'],
  },
  abbreviationLocal: {
    type: String,
    trim: true,
  },
  description: {
    type: String,
    trim: true,
  },
  descriptionLocal: {
    type: String,
    trim: true,
  },
  language: {
    type: languageSchema,
    required: [true, 'language is required'],
  },
  countries: {
    type: [countrySchema],
    default: [],
  },
  type: {
    type: String,
    trim: true,
    default: 'text',
  },
  copyright: {
    type: String,
    trim: true,
  },
  info: {
    type: String,
    trim: true,
  },
  audioBibles: {
    type: [Schema.Types.Mixed],
    default: [],
  },
  created: {
    type: Date,
    default: Date.now,
  },
  updated: {
    type: Date,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
});

bibleSchema.pre<IBible>('save', function (next) {
  this.updated = new Date();
  this.updatedAt = new Date();
  next();
});

export const Bible = mongoose.model<IBible>('Bible', bibleSchema);
export default Bible;
